In [4]:
import pandas as pd

# open the Validation_Calibration_Storm_Selection.xlsx as a dataframe
df = pd.read_excel(r"LWI_Validation_Calibration_Storm_Selection.xlsx", sheet_name="Sheet1")

df

,Name,Start Date,End Date,Season,Storm Surge Magnitude,Rainfall Magnitude,Type of Storm,Duration,Region,Historical coastal run availability (In prev. LWI runs or not),AORC Precipitation Availability (from 2017),USGS Streamflow No. of Gages Availability (from 2017),USGS HWMs data,Notes,ADCIRC Data on Rougarou
0,Isidore,2002-09-01,NaT,Summer,Low,High,Tropical,NaN,"6, 7",Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
1,Oct-02,2002-10-01,NaT,Fa ll,Low,Medium,Non-Tropical,NaN,6,Yes,NaN,NaN,NaN,"2 storms, 10 days apart",[/twi/work/projects/p00542_cpra_2020_lwi_t01/a...
2,Feb-03,2003-02-01,NaT,Winter,Low,Medium,Non-Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
3,Feb-04,2004-02-01,NaT,Winter,Low,Medium,Non-Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
4,May-04,2004-05-01,NaT,Spring,Low,High,Non-Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
5,Ivan,2004-09-01,NaT,Summer,High,Low,Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
6,Katrina,2005-08-01,NaT,Summer,High,High,Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
7,May-08,2008-05-01,NaT,Spring,Low,High,Non-Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
8,Gustav,2008-08-25,2008-09-07,Summer,High,Moderate,Tropical,Short-term,"5, 6, 7",Yes,NaN,NaN,NaN,Gustav and Ike in the same simulation,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
9,Mar-09,2009-03-01,NaT,NaN,NaN,NaN,Non-Tropical,NaN,7,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
10,Oct-09,2009-10-26,2009-10-29,Fall,NaN,NaN,Non-tropical,Short-term,4,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
11,Lee,2011-09-01,NaT,Summer,High,High,Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
12,Isaac,2012-08-01,NaT,Summer,High,High,Tropical,NaN,"6,7",Yes,NaN,NaN,63.0,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
13,Jan-13,2013-01-10,2013-01-17,Winter,Low,Low,Non-tropical,Long-term,"4, 6",Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
14,Jul-15,2015-07-01,NaT,Summer,Low,Low,Non-Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
15,Oct-15,2015-10-24,2015-11-08,Fa ll,Low,Low,Non-tropical,MultiPeriod,"5, 6",Yes,NaN,NaN,NaN,"2 storms, 1 day apart",[/twi/work/projects/p00542_cpra_2020_lwi_t01/a...
16,May-16,2016-05-01,NaT,Spring,Low,High,Non-Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
17,May-17,2017-04-25,2017-05-05,Spring,Low,High,Non-tropical,Short-term,"5, 6",Yes,Yes,59.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
18,Jun-17,2017-06-01,NaT,Summer,Low,High,Non-Tropical,NaN,6,Yes,Yes,59.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
19,Jun-18,2017-06-17,2017-06-21,Summer,NaN,NaN,Non-Tropical,Short-term,4,Yes,Yes,59.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
20,Harvey,2017-08-25,2017-09-01,Summer,NaN,NaN,Tropical,Long-term,4,Yes,Yes,59.0,66.0,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
21,Nate,2017-10-01,NaT,Fa ll,Low,Low,Tropical,NaN,6,Yes,Yes,59.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
22,Mar-18,2018-03-28,2018-03-29,Spring,NaN,NaN,Non-tropical,Short-term,4,Yes,Yes,59.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
23,May-19,2019-05-01,NaT,Spring,Low,High,Non-Tropical,NaN,"6, 7",Yes,Yes,63.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
24,Jun-19,2019-06-01,NaT,Summer,Low,High,Non-Tropical,NaN,6,Yes,Yes,63.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
25,Barry,2019-07-11,2019-07-19,NaN,NaN,NaN,Tropical,Short-term,"5, 6",Yes,Yes,61.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
26,Aug-19,2019-08-01,NaT,NaN,NaN,NaN,Non-Tropical,NaN,7,Yes,Yes,61.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
27,Imelda,2019-09-17,2019-09-19,Fall,NaN,NaN,Tropical,Short-term,4,Yes,Yes,61.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
28,May-20,2020-05-05,2020-05-19,NaN,NaN,NaN,Non-tropical,MultiPeriod,"5, 6",Yes,Yes,61.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
29,Cristobal,2020-06-01,NaT,Summer,High,Low,Tropical,NaN,6,Yes,Yes,61.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
30,Laura,2020-08-20,NaT,NaN,NaN,NaN,Tropical,Short-term,"5, 6",Yes,Yes,61.0,42.0,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
31,Beta_Sally,2020-09-01,NaT,Fa ll,Low,Low,Tropical,NaN,6,Yes,Yes,61.0,1.0,"Is the same period of the Sally storm, so we c...",/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
32,Delta,2020-10-05,2020-10-10,NaN,NaN,NaN,Tropical,Short-term,"4, 5",Yes,Yes,61.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...

In [5]:
# if the column 'End Date' is NaT, use the Start Date + 21 days as the End Date.
df["End Date"] = df["End Date"].fillna(df["Start Date"] + pd.DateOffset(days=21))
df

,Name,Start Date,End Date,Season,Storm Surge Magnitude,Rainfall Magnitude,Type of Storm,Duration,Region,Historical coastal run availability (In prev. LWI runs or not),AORC Precipitation Availability (from 2017),USGS Streamflow No. of Gages Availability (from 2017),USGS HWMs data,Notes,ADCIRC Data on Rougarou
0,Isidore,2002-09-01,2002-09-22,Summer,Low,High,Tropical,NaN,"6, 7",Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
1,Oct-02,2002-10-01,2002-10-22,Fa ll,Low,Medium,Non-Tropical,NaN,6,Yes,NaN,NaN,NaN,"2 storms, 10 days apart",[/twi/work/projects/p00542_cpra_2020_lwi_t01/a...
2,Feb-03,2003-02-01,2003-02-22,Winter,Low,Medium,Non-Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
3,Feb-04,2004-02-01,2004-02-22,Winter,Low,Medium,Non-Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
4,May-04,2004-05-01,2004-05-22,Spring,Low,High,Non-Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
5,Ivan,2004-09-01,2004-09-22,Summer,High,Low,Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
6,Katrina,2005-08-01,2005-08-22,Summer,High,High,Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
7,May-08,2008-05-01,2008-05-22,Spring,Low,High,Non-Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
8,Gustav,2008-08-25,2008-09-07,Summer,High,Moderate,Tropical,Short-term,"5, 6, 7",Yes,NaN,NaN,NaN,Gustav and Ike in the same simulation,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
9,Mar-09,2009-03-01,2009-03-22,NaN,NaN,NaN,Non-Tropical,NaN,7,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
10,Oct-09,2009-10-26,2009-10-29,Fall,NaN,NaN,Non-tropical,Short-term,4,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
11,Lee,2011-09-01,2011-09-22,Summer,High,High,Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
12,Isaac,2012-08-01,2012-08-22,Summer,High,High,Tropical,NaN,"6,7",Yes,NaN,NaN,63.0,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
13,Jan-13,2013-01-10,2013-01-17,Winter,Low,Low,Non-tropical,Long-term,"4, 6",Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
14,Jul-15,2015-07-01,2015-07-22,Summer,Low,Low,Non-Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
15,Oct-15,2015-10-24,2015-11-08,Fa ll,Low,Low,Non-tropical,MultiPeriod,"5, 6",Yes,NaN,NaN,NaN,"2 storms, 1 day apart",[/twi/work/projects/p00542_cpra_2020_lwi_t01/a...
16,May-16,2016-05-01,2016-05-22,Spring,Low,High,Non-Tropical,NaN,6,Yes,NaN,NaN,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
17,May-17,2017-04-25,2017-05-05,Spring,Low,High,Non-tropical,Short-term,"5, 6",Yes,Yes,59.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
18,Jun-17,2017-06-01,2017-06-22,Summer,Low,High,Non-Tropical,NaN,6,Yes,Yes,59.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
19,Jun-18,2017-06-17,2017-06-21,Summer,NaN,NaN,Non-Tropical,Short-term,4,Yes,Yes,59.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
20,Harvey,2017-08-25,2017-09-01,Summer,NaN,NaN,Tropical,Long-term,4,Yes,Yes,59.0,66.0,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
21,Nate,2017-10-01,2017-10-22,Fa ll,Low,Low,Tropical,NaN,6,Yes,Yes,59.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
22,Mar-18,2018-03-28,2018-03-29,Spring,NaN,NaN,Non-tropical,Short-term,4,Yes,Yes,59.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
23,May-19,2019-05-01,2019-05-22,Spring,Low,High,Non-Tropical,NaN,"6, 7",Yes,Yes,63.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
24,Jun-19,2019-06-01,2019-06-22,Summer,Low,High,Non-Tropical,NaN,6,Yes,Yes,63.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
25,Barry,2019-07-11,2019-07-19,NaN,NaN,NaN,Tropical,Short-term,"5, 6",Yes,Yes,61.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
26,Aug-19,2019-08-01,2019-08-22,NaN,NaN,NaN,Non-Tropical,NaN,7,Yes,Yes,61.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
27,Imelda,2019-09-17,2019-09-19,Fall,NaN,NaN,Tropical,Short-term,4,Yes,Yes,61.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
28,May-20,2020-05-05,2020-05-19,NaN,NaN,NaN,Non-tropical,MultiPeriod,"5, 6",Yes,Yes,61.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
29,Cristobal,2020-06-01,2020-06-22,Summer,High,Low,Tropical,NaN,6,Yes,Yes,61.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
30,Laura,2020-08-20,2020-09-10,NaN,NaN,NaN,Tropical,Short-term,"5, 6",Yes,Yes,61.0,42.0,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
31,Beta_Sally,2020-09-01,2020-09-22,Fa ll,Low,Low,Tropical,NaN,6,Yes,Yes,61.0,1.0,"Is the same period of the Sally storm, so we c...",/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...
32,Delta,2020-10-05,2020-10-10,NaN,NaN,NaN,Tropical,Short-term,"4, 5",Yes,Yes,61.0,NaN,NaN,/twi/work/projects/p00542_cpra_2020_lwi_t01/ad...

In [7]:
# use the df name column to make a list is names
names = df["Name"].tolist()
print(names)

['Isidore', 'Oct-02', 'Feb-03', 'Feb-04', 'May-04', 'Ivan', 'Katrina', 'May-08', 'Gustav', 'Mar-09', 'Oct-09', 'Lee', 'Isaac', 'Jan-13', 'Jul-15', 'Oct-15', 'May-16', 'May-17', 'Jun-17', 'Jun-18', 'Harvey', 'Nate', 'Mar-18', 'May-19', 'Jun-19', 'Barry', 'Aug-19', 'Imelda', 'May-20', 'Cristobal', 'Laura', 'Beta_Sally', 'Delta']